@rooms = room
@assets = assets
@reqpath = http://localhost:3000
###
# @name GetRoomsWithAssets
GET {{reqpath}}/{{rooms}}/roomWithAssets/665a3ad6-7415-4a54-91a6-1679cafee0f5
#49d3f0c0-6ed5-4d6f-9877-475ec0366c03
###
# @name GetRooms
GET  {{reqpath}}/{{rooms}}/

{}
###
# @name CreateAssets
POST {{reqpath}}/{{assets}}/

###
# 
GET {{reqpath}}/report


###
export class CreateAssetDto {
  @IsString()
  @IsNotEmpty()
  name: string;

  @IsString()
  @IsNotEmpty()
  room: string;

  @IsString()
  @IsOptional()
  responsiblePerson: string;

  @IsNumber()
  depreciation: number;

  @IsDateString()
  acquisitionDate: Date;
}